### ISSUE TITLE
Peer Review - Connor Jackson

### ISSUE THREAD

**Issue by ConnorJ88** [PenguinJB/OOP-Assessment-1#1]
Is the code properly documented/commented?

- The code is properly documented, with 3 files; Pack, Program and Card

- The comments are very good. They are useful and fairly often but doesn't repeat comments for any repeated code, reducing clutter

- I have no Improvements to suggest about comments or documentation.

**Comment by ConnorJ88** [comment]
Does the code handle errors properly?

- There is clear evidence of error handling throughout the code, such as not allowing the user to put in an integer that is out of range

- However if the user is to input something that can't be converted to an integer the code crashes, this is the case for all user inputs

- However as I mentioned earlier there is clear evidence of basic error handling which is a good start.

**Comment by ConnorJ88** [comment]
What suggestions do you have to improve the code?

- The only suggestions I have to improving the code would be to just implement the advanced error handling which I pointed at before and perhaps add a test class if you really want those higher grades, apart from that the code is very good, performs the two shuffles and therefore does exactly as asked by the brief.

**Comment by PenguinJB** [comment]
Thanks Pal :)

I will add more error handling to avoid crashes
