### ISSUE TITLE
Peer Review - Lewis

### ISSUE THREAD

**Issue by lgibson0511** [PenguinJB/OOP-Assessment-1#2]
Is the code properly documented/commented?
-The code is properly formatted and the comments are clear
-This makes it easy to follow and understand

Does the code handle errors properly?
-There is some evidence of error handling but isn't consistent throughout the code
-For example, when asking if you want to draw one or multiple cards it can take invalid inputs like strings or numbers which are out of range

What suggestions do you have to improve the code?
-I would make sure all user inputs have error handling as previously mentioned
-I would also make it able to shuffle more than once

**Comment by PenguinJB** [comment]
Thank you, error handling is an essential I need to do more work on.
Adding multiple shuffles is an excellent idea to improve user experience
