### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by MiloB04** [PenguinJB/OOP-Assessment-1#3]
The Code runs smoothly without errors and well documented with concise comments. I think it would be a great improvement to have a separate function for the various tests done to demonstrate the classes' functions separate from **Program.cs**.

I also have to say that the code is very efficient especially through things like the use of enum in the **Card.cs** class, on top of that it performs error handling sufficiently through various checks that make sure the fields and values aren't outside of their expected parameters.

Personally I would improve the code firstly by adding "Console.ReadLine();" at the end of the program so that we have an easier time inspecting the output which is what I did for this review. Other than that further ways to improve the code could be adding more to the output. The input from the user to select the shuffle is great but perhaps showing the entire deck after its shuffled would also help demonstrating the **Pack.CS** class and its methods.

Aside from few nitpicks I think this code is quick and dirty to the point. Keep up the great work!

**Comment by PenguinJB** [comment]
Thank youuuu
